"""The first-login password gate, and the cost of enforcing it.

A temporary password is generated by an administrator, displayed on their
screen, and relayed by hand. Until it is replaced it is a shared secret —
which matters because §50 attributes every grade change and finalization
to a named user, and that attribution is only worth what the credential
behind it is worth. Nothing enforced the replacement; the person could
simply never open the sidebar.

The other half of this file is about **where the check runs**.
`require_role` is called at the top of every page and Streamlit re-runs
the whole script on every widget interaction, so a query there would put
a round trip on every click in the entire app. The flag is therefore
resolved once at login and carried on the session object. That is easy to
undo by accident later, so it is pinned structurally.
"""

import ast
import inspect

from app import auth, user_provisioning


def _user(**kwargs):
    defaults = dict(
        id="00000000-0000-0000-0000-000000000001",
        supabase_auth_user_id="auth-1",
        email="teacher@deped.gov.ph",
        full_name="A TEACHER",
        access_token="tok",
        refresh_token="ref",
        role_codes={"SUBJECT_TEACHER"},
    )
    return auth.AuthUser(**{**defaults, **kwargs})


# --- The flag itself -------------------------------------------------------


def test_an_account_defaults_to_not_being_gated():
    """The gate must be opt-in per account. A default of True would lock
    out every session built anywhere else in the codebase."""
    assert _user().must_change_password is False


def test_null_password_changed_at_is_what_arms_the_gate():
    """NULL means "still on the password an admin issued". Read once, at
    login, and turned into a bool there — see _load_or_provision_user."""
    source = inspect.getsource(auth._load_or_provision_user)
    assert "user.password_changed_at is None" in source
    assert "must_change_password=must_change_password" in inspect.getsource(
        auth._load_or_provision_user
    )


def test_signing_in_stamps_last_login():
    """The column existed from the first migration and nothing ever wrote
    to it, so "has this account ever been used?" was unanswerable."""
    assert "user.last_login_at = datetime.now" in inspect.getsource(
        auth._load_or_provision_user
    )


# --- Cost: the whole reason it is shaped this way --------------------------


def test_require_role_reads_an_attribute_and_never_queries():
    """The most expensive place in this app to put a query. Every page
    calls it, and every click re-runs every page."""
    tree = ast.parse(inspect.getsource(auth.require_role).strip())
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            assert node.func.attr not in ("query", "get", "execute"), (
                f"require_role calls .{node.func.attr}() — the flag must come "
                "from the session object, not the database"
            )


def test_the_flag_is_resolved_at_login_not_at_render():
    """`_load_or_provision_user` runs once per sign-in and already holds a
    session open; the gate rides that rather than opening its own."""
    assert "SessionLocal" in inspect.getsource(auth._load_or_provision_user)
    assert "SessionLocal" not in inspect.getsource(auth.require_role)


# --- Lifting the gate ------------------------------------------------------


def test_changing_the_password_clears_the_flag_in_place():
    """Without this the person stays on the forced page until they sign
    out, having just done exactly what was asked of them."""
    source = inspect.getsource(auth._record_password_change)
    assert "user.must_change_password = False" in source
    assert "password_changed_at = datetime.now" in source


def test_the_flag_is_only_cleared_after_supabase_confirms():
    """Stamping first would lift the gate on a password that was never
    actually set — the person would be locked to a credential they think
    they replaced."""
    source = inspect.getsource(auth.change_password_form)
    update = source.index("update_user")
    record = source.index("_record_password_change")
    assert update < record
    # And it must sit in the `else` of the try, not after the except.
    assert "except Exception as exc:" in source
    assert source.index("except Exception as exc:") < record


def test_resetting_a_password_re_arms_the_gate():
    """Otherwise Reset password hands out a fresh shared secret that never
    has to be replaced — the exact state this feature exists to end."""
    source = inspect.getsource(user_provisioning.reset_password)
    assert "password_changed_at = None" in source


def test_resetting_a_password_still_cannot_change_what_someone_can_do():
    """The existing guarantee, re-checked because reset_password now
    touches the users table. Handing out a password must not widen
    access."""
    tree = ast.parse(inspect.getsource(user_provisioning.reset_password).strip())
    function = tree.body[0]
    body = function.body[1:] if ast.get_docstring(function) else function.body
    names = {
        node.id if isinstance(node, ast.Name) else node.attr
        for statement in body
        for node in ast.walk(statement)
        if isinstance(node, (ast.Name, ast.Attribute))
    }
    assert not {"UserRole", "Role", "role_codes"} & names, f"touches roles: {names}"


# --- No way around it ------------------------------------------------------


def test_no_navigation_is_built_while_the_gate_is_up():
    """Building the menu and letting each page refuse would leave the app
    looking usable with every entry a dead end."""
    source = inspect.getsource(auth).split("def require_role")[0]
    assert "password_change_required" in source

    import pathlib

    entrypoint = (
        pathlib.Path(__file__).resolve().parent.parent / "streamlit_app.py"
    ).read_text(encoding="utf-8")
    assert "elif current_user.must_change_password:" in entrypoint
    gate = entrypoint.index("elif current_user.must_change_password:")
    sidebar = entrypoint.index("with st.sidebar:")
    assert gate < sidebar, "the gate must come before the signed-in branch"


def test_require_role_is_a_backstop_for_a_page_reached_by_url():
    source = inspect.getsource(auth.require_role)
    assert "must_change_password" in source
    assert "st.stop()" in source


def test_the_forced_page_offers_a_way_out():
    """Someone who cannot set a password right now must still be able to
    leave, or a mistyped account is a stuck browser."""
    assert "logout()" in inspect.getsource(auth.password_change_required)
