"""one adviser per section per school year

Revision ID: 14e55ba4624b
Revises: 3380d02f4490
Create Date: 2026-08-10 20:21:31.130903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e55ba4624b'
down_revision: Union[str, Sequence[str], None] = '3380d02f4490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_sections_adviser_per_school_year', 'sections', ['school_year_id', 'adviser_user_id'], unique=True, postgresql_where=sa.text('adviser_user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sections_adviser_per_school_year', table_name='sections', postgresql_where=sa.text('adviser_user_id IS NOT NULL'))
    # ### end Alembic commands ###
