"""initial schema

Revision ID: 3380d02f4490
Revises: 
Create Date: 2026-08-10 12:29:42.244658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3380d02f4490'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_policies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_award_policies'))
    )
    op.create_table('grade_levels',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_levels')),
    sa.UniqueConstraint('code', name=op.f('uq_grade_levels_code'))
    )
    op.create_table('grading_policies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_policies'))
    )
    op.create_table('learners',
    sa.Column('lrn', sa.String(length=12), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('extension_name', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lrn IS NULL OR lrn ~ '^[0-9]{12}$'", name=op.f('ck_learners_lrn_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learners'))
    )
    op.create_index('uq_learners_lrn', 'learners', ['lrn'], unique=True, postgresql_where=sa.text('lrn IS NOT NULL'))
    op.create_table('permissions',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('schools',
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('deped_school_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('schools_division', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('school_head_name', sa.String(), nullable=False),
    sa.Column('school_head_position', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools')),
    sa.UniqueConstraint('deped_school_id', name=op.f('uq_schools_deped_school_id'))
    )
    op.create_table('tracks',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks')),
    sa.UniqueConstraint('code', name=op.f('uq_tracks_code'))
    )
    op.create_table('users',
    sa.Column('supabase_auth_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('supabase_auth_user_id', name=op.f('uq_users_supabase_auth_user_id'))
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('combined_learning_areas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade_level_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], name=op.f('fk_combined_learning_areas_grade_level_id_grade_levels'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combined_learning_areas'))
    )
    op.create_table('export_jobs',
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'FAILED', name='exportjobstatus'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_export_jobs_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    op.create_table('import_jobs',
    sa.Column('job_type', sa.Enum('LEARNERS', 'SUBJECT_CATALOG', 'SUBJECT_PROFILES', 'TERM_GRADES', 'ATTENDANCE', 'SCHOOL_INFO', name='importjobtype'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'VALIDATED', 'CONFIRMED', 'FAILED', name='importjobstatus'), server_default='UPLOADED', nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('imported_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_import_jobs_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_table('learner_admission_records',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('date_of_shs_admission', sa.Date(), nullable=True),
    sa.Column('high_school_completer', sa.Boolean(), nullable=True),
    sa.Column('high_school_general_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('high_school_completion_date', sa.Date(), nullable=True),
    sa.Column('junior_high_school_completer', sa.Boolean(), nullable=True),
    sa.Column('junior_high_school_general_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('previous_school_name', sa.String(), nullable=True),
    sa.Column('previous_school_address', sa.String(), nullable=True),
    sa.Column('pept_passer', sa.Boolean(), nullable=True),
    sa.Column('pept_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pept_examination_date', sa.Date(), nullable=True),
    sa.Column('als_ae_passer', sa.Boolean(), nullable=True),
    sa.Column('als_ae_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('als_ae_examination_date', sa.Date(), nullable=True),
    sa.Column('clc_name', sa.String(), nullable=True),
    sa.Column('clc_address', sa.String(), nullable=True),
    sa.Column('other_eligibility_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_learner_admission_records_learner_id_learners'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_admission_records')),
    sa.UniqueConstraint('learner_id', name=op.f('uq_learner_admission_records_learner_id'))
    )
    op.create_table('report_templates',
    sa.Column('report_type', sa.Enum('SF2', 'SF9_G11', 'SF9_G12', 'SF10', 'TERM_CARD', 'CERTIFICATE', name='reporttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('template_file_path', sa.String(), nullable=False),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_report_templates_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_templates')),
    sa.UniqueConstraint('report_type', 'version_number', name=op.f('uq_report_templates_report_type'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('school_years',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=True),
    sa.Column('recognition_venue', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='schoolyearstatus'), server_default='DRAFT', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_years_school_id_schools'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_years')),
    sa.UniqueConstraint('name', name=op.f('uq_school_years_name'))
    )
    op.create_table('strands',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_strands_track_id_tracks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strands')),
    sa.UniqueConstraint('track_id', 'code', name=op.f('uq_strands_track_id'))
    )
    op.create_table('subject_categories',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_grading_policy_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['default_grading_policy_id'], ['grading_policies.id'], name=op.f('fk_subject_categories_default_grading_policy_id_grading_policies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_subject_categories_code'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_user_roles_granted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('award_policy_versions',
    sa.Column('award_policy_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_school_year_id', sa.UUID(), nullable=False),
    sa.Column('require_complete_record', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('require_no_derogatory_record', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('min_general_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_lowest_final_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('require_no_failed_subject', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tier_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='policyversionstatus'), server_default='DRAFT', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['award_policy_id'], ['award_policies.id'], name=op.f('fk_award_policy_versions_award_policy_id_award_policies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_award_policy_versions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['effective_school_year_id'], ['school_years.id'], name=op.f('fk_award_policy_versions_effective_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_award_policy_versions')),
    sa.UniqueConstraint('award_policy_id', 'version_number', name=op.f('uq_award_policy_versions_award_policy_id'))
    )
    op.create_table('grading_policy_versions',
    sa.Column('grading_policy_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_school_year_id', sa.UUID(), nullable=True),
    sa.Column('passing_grade', sa.Numeric(precision=5, scale=2), server_default='75', nullable=False),
    sa.Column('min_grade', sa.Numeric(precision=5, scale=2), server_default='60', nullable=False),
    sa.Column('max_grade', sa.Numeric(precision=5, scale=2), server_default='100', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='policyversionstatus'), server_default='DRAFT', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_grading_policy_versions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['effective_school_year_id'], ['school_years.id'], name=op.f('fk_grading_policy_versions_effective_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grading_policy_id'], ['grading_policies.id'], name=op.f('fk_grading_policy_versions_grading_policy_id_grading_policies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_policy_versions')),
    sa.UniqueConstraint('grading_policy_id', 'version_number', name=op.f('uq_grading_policy_versions_grading_policy_id'))
    )
    op.create_table('report_generation_logs',
    sa.Column('report_type', sa.Enum('SF2', 'SF9_G11', 'SF9_G12', 'SF10', 'TERM_CARD', 'CERTIFICATE', name='reporttype'), nullable=False),
    sa.Column('report_template_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('readiness_status', sa.Enum('READY', 'WARNING', 'BLOCKED', name='reportreadiness'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], name=op.f('fk_report_generation_logs_generated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_template_id'], ['report_templates.id'], name=op.f('fk_report_generation_logs_report_template_id_report_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_generation_logs'))
    )
    op.create_table('sections',
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('grade_level_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('strand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('adviser_user_id', sa.UUID(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('capacity', sa.SmallInteger(), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['adviser_user_id'], ['users.id'], name=op.f('fk_sections_adviser_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], name=op.f('fk_sections_grade_level_id_grade_levels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_sections_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], name=op.f('fk_sections_strand_id_strands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_sections_track_id_tracks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('school_year_id', 'grade_level_id', 'name', name=op.f('uq_sections_school_year_id'))
    )
    op.create_table('subject_profiles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade_level_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('strand_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], name=op.f('fk_subject_profiles_grade_level_id_grade_levels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], name=op.f('fk_subject_profiles_strand_id_strands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_subject_profiles_track_id_tracks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_profiles'))
    )
    op.create_table('subjects',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('grade_level_id', sa.UUID(), nullable=False),
    sa.Column('subject_category_id', sa.UUID(), nullable=False),
    sa.Column('track_restriction_id', sa.UUID(), nullable=True),
    sa.Column('default_grading_policy_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_grading_policy_id'], ['grading_policies.id'], name=op.f('fk_subjects_default_grading_policy_id_grading_policies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], name=op.f('fk_subjects_grade_level_id_grade_levels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_category_id'], ['subject_categories.id'], name=op.f('fk_subjects_subject_category_id_subject_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_restriction_id'], ['tracks.id'], name=op.f('fk_subjects_track_restriction_id_tracks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code'))
    )
    op.create_table('terms',
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('term_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('attendance_period_start', sa.Date(), nullable=True),
    sa.Column('attendance_period_end', sa.Date(), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('grade_encoding_status', sa.Enum('CLOSED', 'OPEN', name='gradeencodingstatus'), server_default='CLOSED', nullable=False),
    sa.Column('finalization_state', sa.Enum('NOT_STARTED', 'OPEN', 'FOR_REVIEW', 'FINALIZED', name='finalizationstate'), server_default='NOT_STARTED', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_terms_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms')),
    sa.UniqueConstraint('school_year_id', 'term_number', name=op.f('uq_terms_school_year_id'))
    )
    op.create_table('academic_calendar_dates',
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('is_default_class_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_final_class_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('class_day_sequence', sa.Integer(), nullable=True),
    sa.Column('overridden_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['overridden_by_user_id'], ['users.id'], name=op.f('fk_academic_calendar_dates_overridden_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_academic_calendar_dates_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_academic_calendar_dates_term_id_terms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_calendar_dates')),
    sa.UniqueConstraint('school_year_id', 'calendar_date', name=op.f('uq_academic_calendar_dates_school_year_id'))
    )
    op.create_table('attendance_month_status',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'OPEN', 'FOR_REVIEW', 'FINALIZED', name='finalizationstate'), server_default='NOT_STARTED', nullable=False),
    sa.Column('finalized_by_user_id', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopen_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['finalized_by_user_id'], ['users.id'], name=op.f('fk_attendance_month_status_finalized_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reopened_by_user_id'], ['users.id'], name=op.f('fk_attendance_month_status_reopened_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_attendance_month_status_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_attendance_month_status_section_id_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_month_status')),
    sa.UniqueConstraint('section_id', 'year_month', name=op.f('uq_attendance_month_status_section_id'))
    )
    op.create_table('combined_learning_area_components',
    sa.Column('combined_learning_area_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['combined_learning_area_id'], ['combined_learning_areas.id'], name=op.f('fk_combined_learning_area_components_combined_learning_area_id_combined_learning_areas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_combined_learning_area_components_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combined_learning_area_components')),
    sa.UniqueConstraint('subject_id', name=op.f('uq_combined_learning_area_components_subject_id'))
    )
    op.create_table('enrollments',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('grade_level_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_status', sa.Enum('ENROLLED', 'LATE_ENROLLMENT', 'TRANSFERRED_IN', 'TRANSFERRED_OUT', 'NLS', 'DROPPED', 'SHIFTED_IN', 'SHIFTED_OUT', 'COMPLETED', 'GRADUATED', 'OTHER', name='enrollmentstatus'), server_default='ENROLLED', nullable=False),
    sa.Column('derogatory_record', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('general_remarks', sa.String(), nullable=True),
    sa.Column('term1_adviser_comment', sa.String(), nullable=True),
    sa.Column('term2_adviser_comment', sa.String(), nullable=True),
    sa.Column('term3_adviser_comment', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], name=op.f('fk_enrollments_grade_level_id_grade_levels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_enrollments_learner_id_learners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_enrollments_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_enrollments_section_id_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('learner_id', 'school_year_id', name=op.f('uq_enrollments_learner_id'))
    )
    op.create_table('section_subject_offerings',
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('subject_category_id', sa.UUID(), nullable=False),
    sa.Column('grading_policy_version_id', sa.UUID(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('PLACEHOLDER', 'CONFIRMED', name='offeringstatus'), server_default='PLACEHOLDER', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['grading_policy_version_id'], ['grading_policy_versions.id'], name=op.f('fk_section_subject_offerings_grading_policy_version_id_grading_policy_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_section_subject_offerings_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_section_subject_offerings_section_id_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_category_id'], ['subject_categories.id'], name=op.f('fk_section_subject_offerings_subject_category_id_subject_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_section_subject_offerings_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_section_subject_offerings_term_id_terms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_subject_offerings')),
    sa.UniqueConstraint('section_id', 'subject_id', 'term_id', name=op.f('uq_section_subject_offerings_section_id'))
    )
    op.create_table('subject_profile_subjects',
    sa.Column('subject_profile_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term1_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('term2_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('term3_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_elective', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_profile_subjects_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_profile_id'], ['subject_profiles.id'], name=op.f('fk_subject_profile_subjects_subject_profile_id_subject_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_profile_subjects')),
    sa.UniqueConstraint('subject_profile_id', 'subject_id', name=op.f('uq_subject_profile_subjects_subject_profile_id'))
    )
    op.create_table('annual_grade_summaries',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('general_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lowest_final_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('failed_subject_count', sa.SmallInteger(), nullable=True),
    sa.Column('completion_status', sa.Enum('COMPLETE', 'INCOMPLETE', name='completionstatus'), server_default='INCOMPLETE', nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_annual_grade_summaries_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_annual_grade_summaries_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annual_grade_summaries')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_annual_grade_summaries_enrollment_id'))
    )
    op.create_table('attendance_records',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('calendar_date_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'CUTTING', name='attendancestatus'), server_default='PRESENT', nullable=False),
    sa.Column('encoded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['calendar_date_id'], ['academic_calendar_dates.id'], name=op.f('fk_attendance_records_calendar_date_id_academic_calendar_dates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['encoded_by_user_id'], ['users.id'], name=op.f('fk_attendance_records_encoded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_attendance_records_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('enrollment_id', 'calendar_date_id', name=op.f('uq_attendance_records_enrollment_id'))
    )
    op.create_table('combined_learning_area_results',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('combined_learning_area_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('term1_combined', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('term2_combined', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('term3_combined', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remark', sa.Enum('PASSED', 'FAILED', 'INCOMPLETE', name='subjectremark'), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['combined_learning_area_id'], ['combined_learning_areas.id'], name=op.f('fk_combined_learning_area_results_combined_learning_area_id_combined_learning_areas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_combined_learning_area_results_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_combined_learning_area_results_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combined_learning_area_results')),
    sa.UniqueConstraint('enrollment_id', 'combined_learning_area_id', 'school_year_id', name=op.f('uq_combined_learning_area_results_enrollment_id'))
    )
    op.create_table('grade_finalization_records',
    sa.Column('scope_type', sa.Enum('TERM_SECTION_SUBJECT', 'ANNUAL_ENROLLMENT', 'ATTENDANCE_MONTH', name='finalizationscopetype'), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('section_subject_offering_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('finalized_by_user_id', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=False),
    sa.Column('reopened_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopen_reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('FINALIZED', 'REOPENED', name='finalizationrecordstatus'), server_default='FINALIZED', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_grade_finalization_records_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finalized_by_user_id'], ['users.id'], name=op.f('fk_grade_finalization_records_finalized_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reopened_by_user_id'], ['users.id'], name=op.f('fk_grade_finalization_records_reopened_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_subject_offering_id'], ['section_subject_offerings.id'], name=op.f('fk_grade_finalization_records_section_subject_offering_id_section_subject_offerings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_grade_finalization_records_term_id_terms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_finalization_records'))
    )
    op.create_table('learner_awards',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('award_policy_version_id', sa.UUID(), nullable=False),
    sa.Column('award_result', sa.Enum('ELIGIBLE_AWARDED', 'NOT_ELIGIBLE', name='awardresult'), nullable=False),
    sa.Column('award_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('override_by_user_id', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['award_policy_version_id'], ['award_policy_versions.id'], name=op.f('fk_learner_awards_award_policy_version_id_award_policy_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_learner_awards_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['override_by_user_id'], ['users.id'], name=op.f('fk_learner_awards_override_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_learner_awards_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_awards')),
    sa.UniqueConstraint('enrollment_id', 'award_policy_version_id', name=op.f('uq_learner_awards_enrollment_id'))
    )
    op.create_table('learner_movements',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('ENROLLED', 'LATE_ENROLLMENT', 'TRANSFERRED_IN', 'TRANSFERRED_OUT', 'NLS', 'DROPPED', 'SHIFTED_IN', 'SHIFTED_OUT', 'COMPLETED', 'GRADUATED', 'OTHER', name='enrollmentstatus'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('previous_school', sa.String(), nullable=True),
    sa.Column('receiving_school', sa.String(), nullable=True),
    sa.Column('nls_reason', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('encoded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['encoded_by_user_id'], ['users.id'], name=op.f('fk_learner_movements_encoded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_learner_movements_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_movements'))
    )
    op.create_table('subject_final_grades',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('final_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remark', sa.Enum('PASSED', 'FAILED', 'INCOMPLETE', name='subjectremark'), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_subject_final_grades_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_subject_final_grades_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_final_grades_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_final_grades')),
    sa.UniqueConstraint('enrollment_id', 'subject_id', 'school_year_id', name=op.f('uq_subject_final_grades_enrollment_id'))
    )
    op.create_table('teacher_assignments',
    sa.Column('section_subject_offering_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_teacher_assignments_assigned_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_subject_offering_id'], ['section_subject_offerings.id'], name=op.f('fk_teacher_assignments_section_subject_offering_id_section_subject_offerings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], name=op.f('fk_teacher_assignments_teacher_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_assignments'))
    )
    op.create_index('uq_teacher_assignments_active_offering', 'teacher_assignments', ['section_subject_offering_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('term_grades',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('section_subject_offering_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('official_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grading_policy_version_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VERIFIED', 'FINALIZED', name='gradeworkflowstatus'), server_default='DRAFT', nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_by_user_id', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_term_grades_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finalized_by_user_id'], ['users.id'], name=op.f('fk_term_grades_finalized_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grading_policy_version_id'], ['grading_policy_versions.id'], name=op.f('fk_term_grades_grading_policy_version_id_grading_policy_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_jobs.id'], name=op.f('fk_term_grades_import_batch_id_import_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_subject_offering_id'], ['section_subject_offerings.id'], name=op.f('fk_term_grades_section_subject_offering_id_section_subject_offerings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_term_grades_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_term_grades_term_id_terms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_term_grades_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_grades')),
    sa.UniqueConstraint('enrollment_id', 'section_subject_offering_id', 'term_id', name=op.f('uq_term_grades_enrollment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_grades')
    op.drop_index('uq_teacher_assignments_active_offering', table_name='teacher_assignments', postgresql_where=sa.text('is_active'))
    op.drop_table('teacher_assignments')
    op.drop_table('subject_final_grades')
    op.drop_table('learner_movements')
    op.drop_table('learner_awards')
    op.drop_table('grade_finalization_records')
    op.drop_table('combined_learning_area_results')
    op.drop_table('attendance_records')
    op.drop_table('annual_grade_summaries')
    op.drop_table('subject_profile_subjects')
    op.drop_table('section_subject_offerings')
    op.drop_table('enrollments')
    op.drop_table('combined_learning_area_components')
    op.drop_table('attendance_month_status')
    op.drop_table('academic_calendar_dates')
    op.drop_table('terms')
    op.drop_table('subjects')
    op.drop_table('subject_profiles')
    op.drop_table('sections')
    op.drop_table('report_generation_logs')
    op.drop_table('grading_policy_versions')
    op.drop_table('award_policy_versions')
    op.drop_table('user_roles')
    op.drop_table('subject_categories')
    op.drop_table('strands')
    op.drop_table('school_years')
    op.drop_table('role_permissions')
    op.drop_table('report_templates')
    op.drop_table('learner_admission_records')
    op.drop_table('import_jobs')
    op.drop_table('export_jobs')
    op.drop_table('combined_learning_areas')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('tracks')
    op.drop_table('schools')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('uq_learners_lrn', table_name='learners', postgresql_where=sa.text('lrn IS NOT NULL'))
    op.drop_table('learners')
    op.drop_table('grading_policies')
    op.drop_table('grade_levels')
    op.drop_table('award_policies')
    # ### end Alembic commands ###
