"""term summaries and award scope

Revision ID: a5defba95bef
Revises: 14e55ba4624b
Create Date: 2026-08-10 23:31:30.251669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a5defba95bef'
down_revision: Union[str, Sequence[str], None] = '14e55ba4624b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_grade_summaries',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('term_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lowest_term_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('failed_subject_count', sa.SmallInteger(), nullable=True),
    # create_type=False: the completionstatus enum already exists in
    # Postgres (annual_grade_summaries created it). Autogenerate always
    # emits a bare sa.Enum here, which would re-issue CREATE TYPE and
    # fail — reuse the existing type instead.
    sa.Column('completion_status', postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='completionstatus', create_type=False), server_default='INCOMPLETE', nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_term_grade_summaries_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], name=op.f('fk_term_grade_summaries_school_year_id_school_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_term_grade_summaries_term_id_terms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_grade_summaries')),
    sa.UniqueConstraint('enrollment_id', 'term_id', name=op.f('uq_term_grade_summaries_enrollment_id'))
    )
    # op.add_column does NOT auto-create a new enum type the way
    # create_table does, so awardscope has to be created explicitly first.
    award_scope = postgresql.ENUM('TERM', 'ANNUAL', name='awardscope', create_type=False)
    award_scope.create(op.get_bind(), checkfirst=True)
    op.add_column('award_policy_versions', sa.Column('scope', award_scope, server_default='ANNUAL', nullable=False))
    op.add_column('learner_awards', sa.Column('term_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_learner_awards_enrollment_id'), 'learner_awards', type_='unique')
    op.create_index('uq_learner_awards_annual', 'learner_awards', ['enrollment_id', 'award_policy_version_id'], unique=True, postgresql_where=sa.text('term_id IS NULL'))
    op.create_index('uq_learner_awards_term', 'learner_awards', ['enrollment_id', 'award_policy_version_id', 'term_id'], unique=True, postgresql_where=sa.text('term_id IS NOT NULL'))
    op.create_foreign_key(op.f('fk_learner_awards_term_id_terms'), 'learner_awards', 'terms', ['term_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # Data fix, not schema: the new column defaults every existing row to
    # ANNUAL, but the tiered Honors policy is judged per term against the
    # Term Average (§17). Matched by policy name because that's the only
    # stable identifier for a seeded row across environments; a no-op
    # anywhere that policy doesn't exist.
    op.execute(
        """
        UPDATE award_policy_versions AS v
        SET scope = 'TERM'
        FROM award_policies AS p
        WHERE v.award_policy_id = p.id
          AND p.name = 'Legacy Tiered Honors'
        """
    )

    # Any award already computed against a now-TERM-scoped policy was
    # judged on the annual General Average and carries term_id IS NULL,
    # which the new code can neither display (the UI filters by term) nor
    # recompute (compute_award_eligibility needs a term_id for TERM
    # scope). They're unreachable rows, and re-deriving them is one click
    # on the Awards page. Manual overrides are deliberately left alone —
    # those carry a human decision, so they surface for review instead of
    # being discarded.
    op.execute(
        """
        DELETE FROM learner_awards AS la
        USING award_policy_versions AS v
        WHERE la.award_policy_version_id = v.id
          AND v.scope = 'TERM'
          AND la.term_id IS NULL
          AND la.is_override = false
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_learner_awards_term_id_terms'), 'learner_awards', type_='foreignkey')
    op.drop_index('uq_learner_awards_term', table_name='learner_awards', postgresql_where=sa.text('term_id IS NOT NULL'))
    op.drop_index('uq_learner_awards_annual', table_name='learner_awards', postgresql_where=sa.text('term_id IS NULL'))
    op.create_unique_constraint(op.f('uq_learner_awards_enrollment_id'), 'learner_awards', ['enrollment_id', 'award_policy_version_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('learner_awards', 'term_id')
    op.drop_column('award_policy_versions', 'scope')
    op.drop_table('term_grade_summaries')
    # Drop the type this migration created. completionstatus is left
    # alone — it predates this migration and other tables still use it.
    postgresql.ENUM(name='awardscope').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
