"""permanent learner academic record

Revision ID: f00c90460cb9
Revises: a5defba95bef
Create Date: 2026-08-11 14:41:18.510202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f00c90460cb9'
down_revision: Union[str, Sequence[str], None] = 'a5defba95bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_academic_records',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('lrn', sa.String(), nullable=True),
    sa.Column('learner_name', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('deped_school_id', sa.String(), nullable=True),
    sa.Column('school_year_name', sa.String(), nullable=False),
    sa.Column('grade_level', sa.String(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('track_name', sa.String(), nullable=True),
    sa.Column('strand_name', sa.String(), nullable=True),
    sa.Column('general_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('general_average_remark', sa.String(), nullable=True),
    # create_type=False: completionstatus already exists (annual_grade_summaries
    # created it). Autogenerate always emits a bare sa.Enum here, which would
    # re-issue CREATE TYPE and fail.
    sa.Column('completion_status', postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='completionstatus', create_type=False), server_default='INCOMPLETE', nullable=False),
    sa.Column('award_name', sa.String(), nullable=True),
    sa.Column('passing_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grading_policy_version_id', sa.UUID(), nullable=True),
    sa.Column('grading_policy_label', sa.String(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('snapshot_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_learner_academic_records_enrollment_id_enrollments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grading_policy_version_id'], ['grading_policy_versions.id'], name=op.f('fk_learner_academic_records_grading_policy_version_id_grading_policy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_learner_academic_records_learner_id_learners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_by_user_id'], ['users.id'], name=op.f('fk_learner_academic_records_snapshot_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_academic_records')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_learner_academic_records_enrollment_id'))
    )
    op.create_table('learner_academic_record_subjects',
    sa.Column('learner_academic_record_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('subject_category', sa.String(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('offered_term1', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('offered_term2', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('offered_term3', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('term1_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('term2_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('term3_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('is_combined_parent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_component', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('component_final_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_academic_record_id'], ['learner_academic_records.id'], name=op.f('fk_learner_academic_record_subjects_learner_academic_record_id_learner_academic_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_learner_academic_record_subjects_subject_id_subjects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_academic_record_subjects'))
    )
    op.create_table('learner_academic_record_terms',
    sa.Column('learner_academic_record_id', sa.UUID(), nullable=False),
    sa.Column('term_number', sa.SmallInteger(), nullable=False),
    sa.Column('term_name', sa.String(), nullable=True),
    sa.Column('term_average', sa.Numeric(precision=5, scale=2), nullable=True),
    # create_type=False: completionstatus already exists (annual_grade_summaries
    # created it). Autogenerate always emits a bare sa.Enum here, which would
    # re-issue CREATE TYPE and fail.
    sa.Column('completion_status', postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='completionstatus', create_type=False), server_default='INCOMPLETE', nullable=False),
    sa.Column('award_name', sa.String(), nullable=True),
    sa.Column('adviser_comment', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_academic_record_id'], ['learner_academic_records.id'], name=op.f('fk_learner_academic_record_terms_learner_academic_record_id_learner_academic_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_academic_record_terms'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_academic_record_terms')
    op.drop_table('learner_academic_record_subjects')
    op.drop_table('learner_academic_records')
    # ### end Alembic commands ###
